### ISSUE TITLE
[doc] Issue in "Custom files section:" Duplicate metal3-media: section

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#270]
Custom files section::

https://documentation.suse.com/suse-edge/1.0/html/edge/atip-management-cluster.html#mgmt-cluster-helm-values

```
global:
  ironicIP: ${MGMT_CLUSTER_IP}
  enable_vmedia_tls: false
  enable_metal3_media_server: true

metal3-media:
  service:
    type: NodePort
    port: 6280

metal3-ironic:
  global:
    predictableNicNames: "true"
  service:
    type: NodePort

metal3-media:
  mediaVolume:
    hostPath: ${MEDIA_VOLUME_PATH}
```
