### ISSUE TITLE
[doc] Issue in "Management cluster definition file"

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#278]
Management cluster definition file:

https://suse-edge.github.io/atip-management-cluster.html#mgmt-cluster-image-definition-file

Unify file names in the second `kubernetes:`

```
    nodes:
      - hostname: mgmt-cluster1 ---> mgmt-cluster-node-1
        initializer: true
        type: server
#      - hostname: mgmt-cluster2 ---> mgmt-cluster-node-2
#        type: server
#      - hostname: mgmt-cluster3 ---> mgmt-cluster-node-3
#        type: server
```
