### ISSUE TITLE
[doc] Issue in "Downstream cluster provisioning with Directed network provisioning (multi-node)" -  RolloutStrategy missing from RKE2ControlPlane manifest

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#557]
```
  rolloutStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 0
```
