### ISSUE TITLE
[doc] Issue in "Downstream cluster provisioning with Directed network provisioning (multi-node)" - Extra \ in MetalLB config

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#581]
```
- path: /var/lib/rancher/rke2/server/manifests/metallb-cr.yaml
              overwrite: true
              contents:
                inline: |
                  apiVersion: metallb.io/v1beta1
                  kind: IPAddressPool
                  metadata:
                    name: kubernetes-vip-ip-pool
                    namespace: metallb-system
                  spec:
                    addresses:
                      - ${EDGE_VIP_ADDRESS}/32
                    serviceAllocation:
                      priority: 100
                      namespaces:
                        - default
                      serviceSelectors:
                        - matchExpressions:
                          - \{key: "serviceType", operator: In, values: [kubernetes-vip]}
```
The last line has an extra `\` in the beginning restricting the `kubernetes-vip` to be properly set in load-balanced configuration.
