### ISSUE TITLE
[doc] Issue in "Installing the Endpoint Copier Operator"

### ISSUE THREAD

**Issue by LMSSonos** [suse-edge/suse-edge.github.io#611]
In the following snipped the I think the port should be `6443` as for RKE2 - at least in my setup i changed that ;-)

```
cat <<-EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-vip
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443  <!---------------------- should be 6443 ------------------->
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: LoadBalancer
EOF
```
