### ISSUE TITLE
[doc] Issue in "Installing MetalLB" - Is ip-pool necessary here?

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#619]
```
cat <<-EOF | kubectl apply -f -
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ip-pool-l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool
  - kubernetes-vip-ip-pool
EOF
```
