### ISSUE TITLE
[doc] "(Optionally) Install the Elemental UI extension" EIB/helm instructions missing.

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/suse-edge.github.io#631]
(Optionally) Install the Elemental UI extension:

https://documentation.suse.com/suse-edge/3.1/html/edge/quickstart-elemental.html#id-optionally-install-the-elemental-ui-extension only shows the UI side of things. It would be nice to include instructions on how to do it via EIB and/or helm.

Just in case, this is what I use to deploy elemental and the elemental ui with different approaches:

Via helm install:

```
helm install --create-namespace -n cattle-elemental-system \
 elemental-operator-crds \
 oci://registry.suse.com/rancher/elemental-operator-crds-chart \
 --version 1.6.5

helm install -n cattle-elemental-system \
 elemental-operator \
 oci://registry.suse.com/rancher/elemental-operator-chart \
 --version 1.6.5
 
helm install -n cattle-ui-plugin-system \
 elemental elemental \
 --repo https://github.com/rancher/ui-plugin-charts/raw/main \
 --version 3.0.0
```

Via EIB:

```
      - createNamespace: true
        installationNamespace: kube-system
        name: elemental-operator-crds-chart
        repositoryName: elemental-operator-crds-chart
        targetNamespace: cattle-elemental-system
        version: 1.6.5
      - createNamespace: true
        installationNamespace: kube-system
        name: elemental-operator-chart
        repositoryName: elemental-operator-chart
        targetNamespace: cattle-elemental-system
        version: 1.6.5
      - createNamespace: true
        installationNamespace: kube-system
        name: elemental
        repositoryName: elementalui
        targetNamespace: cattle-ui-plugin-system
        version: 3.0.0
# repos  
     - name: elemental-operator-crds-chart
        url: oci://registry.suse.com/rancher
     - name: elemental-operator-chart
        url: oci://registry.suse.com/rancher
     - name: elementalui
        url: https://github.com/rancher/ui-plugin-charts/raw/main
```

Via Rancher:

```
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: rancher-ui-plugins
spec:
  gitBranch: main
  gitRepo: https://github.com/rancher/ui-plugin-charts
---
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: rancher-rke2-charts
spec:
  gitBranch: main
  gitRepo: https://git.rancher.io/rke2-charts
---
apiVersion: catalog.cattle.io/v1
kind: UIPlugin
metadata:
  name: elemental
  namespace: cattle-ui-plugin-system
spec:
  plugin:
    endpoint: https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/extensions/elemental/3.0.1
    name: elemental
    noAuth: false
    noCache: false
    version: 3.0.1
```
